### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by daizhonghao** [hengzhe-zhang/EvolutionaryForest#73]
* Evolutionary Forest version: 0.1.7
* Python version: 3.6.0
* Operating System: linux

### Description
Hi, there. Is parallel supported in this package. I notice there is a param "n_process", but when I use a dataset with #50_0000 times 100 featues, the program stucks there and I dont what is going on.
![企业微信截图_16442195086386](https://user-images.githubusercontent.com/27004710/152745023-dbcc2be5-d6b1-4e5a-aef2-8e68520cd5cf.png)

**Comment by zhenlingcn** [comment]
Undoubtedly, parallel computing is supported by this package, and it is recommended to set the number of processes equal to the number of your computer processors. Moreover, to ascertain the reason for this fault, I suggest you run this package on a smaller dataset in scikit-learn to see whether parallel computing is supported by your computer.

**Comment by daizhonghao** [comment]
> Undoubtedly, parallel computing is supported by this package, and it is recommended to set the number of processes equal to the number of your computer processors. Moreover, to ascertain the reason for this fault, I suggest you run this package on a smaller dataset in scikit-learn to see whether parallel computing is supported by your computer.

Hi, thanks for your quick reply. I tried a small dataset and it works. The parallel computing is supported on my computer. Do you have any requirements for the lightgbm version?

**Comment by zhenlingcn** [comment]
No, our package does not use LightGBM now. If you have a large dataset, use the tournament selection operator, e.g. "Tournament-7", instead of the lexicase selection operator might be a better choice. The speed of lexicase selection operator will be significantly improved in the next version of this package.

**Comment by daizhonghao** [comment]
> No, our package does not use LightGBM now. If you have a large dataset, use the tournament selection operator, e.g. "Tournament-7", instead of the lexicase selection operator might be a better choice. The speed of lexicase selection operator will be significantly improved in the next version of this package.

Hi, thanks for your suggestion. I will try this setup. Again, thanks for you providing this useful tool
