### ISSUE TITLE
The question about the following errors

### ISSUE THREAD

**Issue by lxb123456** [hengzhe-zhang/EvolutionaryForest#75]
### When I created the environment and run the first simple case of Zhihu, I encountered the following errors. I hope the author can reply at his free time, thanks!
![error_1](https://user-images.githubusercontent.com/51871873/177122805-2d6d018d-e4fa-4430-97a7-ac91a2a76980.JPG)
![error](https://user-images.githubusercontent.com/51871873/177122821-3996fc06-3da7-4f5f-98b0-822ac78ae5d1.JPG)
![error2](https://user-images.githubusercontent.com/51871873/177122827-11eef419-65cf-45d0-8330-1b045b0dfba8.JPG)

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by lxb123456** [comment]
Thanks for your review. I set  the hyper-parameter "n_process" as  one to solve this problem. I want to futher ask that the title of your paper is "An Evolutionary Forest for Regression" ?

**Comment by hengzhe-zhang** [comment]
Yeah, that's correct.

**Comment by lxb123456** [comment]
Ok, Thanks for your reply.
