### ISSUE TITLE
dictionary changed size during iteration

### ISSUE THREAD

**Issue by arashag** [hengzhe-zhang/EvolutionaryForest#76]
* Evolutionary Forest version:
* Python version:
* Operating System:

### Description
I tried to run the example provided in the documentation using Google Colab however I received the following error.

### What I Did

```
import random

import numpy as np
#from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
from sklearn.datasets import load_diabetes
from sklearn.ensemble import ExtraTreesRegressor, AdaBoostRegressor, GradientBoostingRegressor, RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

from evolutionary_forest.forest import EvolutionaryForestRegressor
from evolutionary_forest.utils import get_feature_importance, plot_feature_importance, feature_append

random.seed(0)
np.random.seed(0)

# Load Dataset
X, y = load_diabetes(return_X_y=True)
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Train Evolutionary Forest
r = EvolutionaryForestRegressor(max_height=3, normalize=True, select='AutomaticLexicase',
                                gene_num=10, boost_size=100, n_gen=20, n_pop=200, cross_pb=1,
                                base_learner='Random-DT', verbose=True, n_process=64)
r.fit(x_train, y_train)
print(r2_score(y_test, r.predict(x_test)))

```

and received the following traceback:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-26-95cdef9fb681>](https://localhost:8080/#) in <module>()
      3                                 gene_num=10, boost_size=100, n_gen=20, n_pop=200, cross_pb=1,
      4                                 base_learner='Random-DT', verbose=True, n_process=64)
----> 5 r.fit(x_train, y_train)
      6 print(r2_score(y_test, r.predict(x_test)))

2 frames
[/usr/local/lib/python3.7/dist-packages/evolutionary_forest/forest.py](https://localhost:8080/#) in fit(self, X, y)
    585 
    586         pop, log = self.eaSimple(self.pop, self.toolbox, self.cross_pb, self.mutation_pb, self.n_gen,
--> 587                                  stats=mstats, halloffame=self.hof, verbose=self.verbose)
    588         self.pop = pop
    589 

[/usr/local/lib/python3.7/dist-packages/evolutionary_forest/forest.py](https://localhost:8080/#) in eaSimple(self, population, toolbox, cxpb, mutpb, ngen, stats, halloffame, verbose)
    842 
    843         record = stats.compile(population) if stats else {}
--> 844         logbook.record(gen=0, nevals=len(invalid_ind), **record)
    845         if verbose:
    846             print(logbook.stream)

[/usr/local/lib/python3.7/dist-packages/deap/tools/support.py](https://localhost:8080/#) in record(self, **infos)
    336         """
    337         apply_to_all = {k: v for k, v in infos.items() if not isinstance(v, dict)}
--> 338         for key, value in infos.items():
    339             if isinstance(value, dict):
    340                 chapter_infos = value.copy()

RuntimeError: dictionary changed size during iteration

**Comment by hengzhe-zhang** [comment]
Thanks for providing this error. It's a problem caused by the latest version of DEAP (https://github.com/DEAP/deap/issues/662). They released a new version four hours ago, and I believe this is the reason for this failure. A quick solution might be to degrade the version of DEAP to v1.3.1. Thanks!
