### ISSUE TITLE
Cannot Pickle the final model

### ISSUE THREAD

**Issue by arashag** [hengzhe-zhang/EvolutionaryForest#77]
* Evolutionary Forest version:
* Python version:
* Operating System:

### Description

I tried to pickle the final model, and save it into the disk using Colab. However, I received the following error. Furthermore, I tried joblib and dill packages but received the same error.

### What I Did

```
with open('test.pkl', 'wb') as file:  
    pickle.dump(r, file)
```

Exception:
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
[<ipython-input-14-f89b1e4ec501>](https://localhost:8080/#) in <module>()
      1 with open(f'{curr}.pkl', 'wb') as file:
----> 2     pickle.dump(r, file)

PicklingError: Can't pickle <function cxOnePoint_multiple_gene at 0x7f7adbcde320>: it's not the same object as evolutionary_forest.multigene_gp.cxOnePoint_multiple_gene

**Comment by hengzhe-zhang** [comment]
Sorry, I'm not sure what is the reason for this error. Maybe you can see my codes about [how to pickle the final model](https://colab.research.google.com/drive/1TO9TVZle2kWd8Mcvw6AbSV9l8rf0MXfU?usp=sharing) to find the reason.

**Comment by arashag** [comment]
It worked for me. I think the issue might be due to the `pool` attribute that should be deleted.
