### ISSUE TITLE
feature_append 报错

### ISSUE THREAD

**Issue by kakalovedata** [hengzhe-zhang/EvolutionaryForest#79]
new_train = feature_append(r, x_train, list(code_importance_dict.keys())[:len(code_importance_dict.keys()) // 2], only_new_features=True)

这里报错：
TypeError: <lambda>() takes 10 positional arguments but 4638 were given

背景：我只想用特征工程，输入df ，产生new_df 然后路径是这样写的。

r.fit(x, y)
ture_importance_dict = get_feature_importance(r)
code_importance_dict = get_feature_importance(r, simple_version=False)
new_x = feature_append(r, x, list(code_importance_dict.keys())[:len(code_importance_dict.keys())],only_new_features=True)

![image](https://user-images.githubusercontent.com/74294953/192544495-cd965fba-c6c4-456e-90a0-6888dcaf4819.png)

**Comment by kakalovedata** [comment]
我的 x是一个df的几个列 ，没有转化成矩阵形式，可能是这个原因。

**Comment by hengzhe-zhang** [comment]
目前版本暂时不支持DataFrame格式，请转换成Numpy格式再试试。

**Comment by kakalovedata** [comment]
好的，谢谢，我昨天也意识到了这个。

**Comment by kakalovedata** [comment]
您好，麻烦请教下，新特征的列名 用哪个函数获取？

**Comment by hengzhe-zhang** [comment]
抱歉现在才回复，新特征的列名可以通过`get_feature_importance(r, simple_version=True)`来获得。至于兼容DF，我争取在2022年结束之前兼容DF。

**Comment by hengzhe-zhang** [comment]
Evolutionary Forest now supports the DataFrame format. Please refer to the tutorial at https://github.com/hengzhe-zhang/EvolutionaryForest/blob/master/tutorial/pandas_support.ipynb.
