### ISSUE TITLE
可以替换掉smt的抽样方法？

### ISSUE THREAD

**Issue by cfkstat** [hengzhe-zhang/EvolutionaryForest#80]
安装起来难度过大.
![image](https://user-images.githubusercontent.com/24238907/218356563-0febd916-6921-4638-af4f-31fddd030215.png)

**Comment by hengzhe-zhang** [comment]
您好，SMT不是强制依赖，可以选择不安装。应该不会影响程序正常运行。

**Comment by cfkstat** [comment]
用pyDOE的抽样算法可以替换不？

**Comment by hengzhe-zhang** [comment]
抱歉回复晚了，目前Evolutionary Forest中是不需要采样的，因此实际上不需要安装smt依赖，因为历史遗留代码的原因，所以才将SMT保留了。不过，还是感谢您的建议，以后会考虑使用pyDOE处理未来可能涉及采样的情况。
