### ISSUE TITLE
Updating Requirements.txt

### ISSUE THREAD

**Issue by minghao51** [hengzhe-zhang/EvolutionaryForest#82]
* Evolutionary Forest version: 1.0
* Python version: 3.8
* Operating System: WSL

### Description
Should requirements.txt be updated?
I did manage to the example nb, but had to manually pip install **gplearn, scorch, umap-learn, category_encoders.**

**Also, are all the packages required/essesntial? (As in, they aren't relics of previous exploration or optional)? **

## Background
I was attempting to setup a blank environment for EvolutionaryForest with mamba but run into various issues with python package dependencies.

### Environment setup

The final environment.yaml that I used.

```text
name: evolutionforest

channels:
  - conda-forge

dependencies:
  - jupyter-packaging
  - jupyterlab
  - nodejs
  - pytest
  - pytest-check-links
  - python=3.9
  - yarn
  - seaborn
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - pip
  - pip:
    - gplearn
    - shap
    - pyade
    - scorch
    - umap-learn
    - category_encoders
    - evolutionary_forest
```

and also, on WSL ubuntu

```
sudo apt-get install gcc
sudo apt-get install g++
```

**Comment by hengzhe-zhang** [comment]
Thank you very much! I will update the README file. Moreover, there are indeed numerous redundant packages, and I will make an effort to clean up the code in the future.

**Comment by hengzhe-zhang** [comment]
I have updated the requirements file on GitHub. Now, I believe the package can automatically install the required packages using the following command.

``
pip install git+https://github.com/hengzhe-zhang/EvolutionaryForest.git
```

**Comment by minghao51** [comment]
i tired using it, run into missing 'pyade' though?
![image](https://github.com/hengzhe-zhang/EvolutionaryForest/assets/9652472/2525def7-c2ba-47d8-9f10-3e03172e0c5d)

**Comment by hengzhe-zhang** [comment]
Sorry, I was attending GECCO these days. I'm back in the office now, and I've updated the requirement file. 
https://github.com/hengzhe-zhang/EvolutionaryForest/blob/master/requirements.txt
I believe this version is correct, and I have successfully install this package in a completely new virtual environment.
