### ISSUE TITLE
关于采用其他数据集测试后，模型性能提升效果不好的问题

### ISSUE THREAD

**Issue by TangWenYing** [hengzhe-zhang/EvolutionaryForest#84]
* Evolutionary Forest version: 0.1.7
* Python version: 3.9.7
* Operating System: Windows

### Description

我们使用了新的数据集在示例代码中实验，但是在实验过程中，采用演化森林后，许多模型的效果并没有得到提升。但是根据演化森林的理论，应该是可以得到提升的。希望能够得到您的解答，谢谢！

**Comment by hengzhe-zhang** [comment]
如果您有后续反馈，欢迎重新开启issue。
