### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'"

### ISSUE THREAD

**Issue by YinMengjiao** [hengzhe-zhang/EvolutionaryForest#86]
* Evolutionary Forest version: 最新的
* Python version: 3.9
* Operating System: Windows

作者您好！
我用你的tutorial的例子跑，现在不行了，应该是我用的某个依赖库的版本和你不同？
请问怎么才能跑通？能不降版本吗

--------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 10
      7 from sklearn.metrics import r2_score
      8 from sklearn.model_selection import train_test_split
---> 10 from evolutionary_forest.forest import EvolutionaryForestRegressor
     12 random.seed(0)
     13 np.random.seed(0)

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\evolutionary_forest\\forest.py:22
     20 from sklearn.base import RegressorMixin, BaseEstimator, ClassifierMixin, TransformerMixin
     21 from sklearn.cluster import KMeans
---> 22 from sklearn.compose.tests.test_target import DummyTransformer
     23 from sklearn.decomposition import PCA
     24 from sklearn.ensemble import ExtraTreesRegressor, GradientBoostingRegressor, RandomForestClassifier, \\
     25     RandomForestRegressor

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\sklearn\\compose\\tests\\test_target.py:11
      9 from sklearn.pipeline import Pipeline
     10 from sklearn.preprocessing import FunctionTransformer, StandardScaler
---> 11 from sklearn.utils._testing import assert_allclose, assert_no_warnings
     13 friedman = datasets.make_friedman1(random_state=0)
     16 def test_transform_target_regressor_error():

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\sklearn\\utils\\_testing.py:371
    368 skip_if_32bit = pytest.mark.skipif(_IS_32BIT, reason=\"skipped on 32bit platforms\")
    369 fails_if_pypy = pytest.mark.xfail(IS_PYPY, reason=\"not compatible with PyPy\")
    370 fails_if_unstable_openblas = pytest.mark.xfail(
--> 371     _in_unstable_openblas_configuration(),
    372     reason=\"OpenBLAS is unstable for this configuration\",
    373 )
    374 skip_if_no_parallel = pytest.mark.skipif(
    375     not joblib.parallel.mp, reason=\"joblib is in serial mode\"
    376 )
    377 skip_if_array_api_compat_not_configured = pytest.mark.skipif(
    378     not ARRAY_API_COMPAT_FUNCTIONAL,
    379     reason=\"requires array_api_compat installed and a new enough version of NumPy\",
    380 )

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\sklearn\\utils\\__init__.py:89, in _in_unstable_openblas_configuration()
     86 import numpy  # noqa
     87 import scipy  # noqa
---> 89 modules_info = threadpool_info()
     91 open_blas_used = any(info[\"internal_api\"] == \"openblas\" for info in modules_info)
     92 if not open_blas_used:

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\sklearn\\utils\\fixes.py:85, in threadpool_info()
     83     return controller.info()
     84 else:
---> 85     return threadpoolctl.threadpool_info()

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:124, in threadpool_info()
    107 @_format_docstring(USER_APIS=list(_ALL_USER_APIS),
    108                    INTERNAL_APIS=_ALL_INTERNAL_APIS)
    109 def threadpool_info():
    110     \"\"\"Return the maximal number of threads for each detected library.
    111 
    112     Return a list with all the supported modules that have been found. Each
   (...)
    122     In addition, each module may contain internal_api specific entries.
    123     \"\"\"
--> 124     return _ThreadpoolInfo(user_api=_ALL_USER_APIS).todicts()

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:340, in _ThreadpoolInfo.__init__(self, user_api, prefixes, modules)
    337     self.user_api = [] if user_api is None else user_api
    339     self.modules = []
--> 340     self._load_modules()
    341     self._warn_if_incompatible_openmp()
    342 else:

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:373, in _ThreadpoolInfo._load_modules(self)
    371     self._find_modules_with_dyld()
    372 elif sys.platform == \"win32\":
--> 373     self._find_modules_with_enum_process_module_ex()
    374 else:
    375     self._find_modules_with_dl_iterate_phdr()

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:485, in _ThreadpoolInfo._find_modules_with_enum_process_module_ex(self)
    482         filepath = buf.value
    484         # Store the module if it is supported and selected
--> 485         self._make_module_from_path(filepath)
    486 finally:
    487     kernel_32.CloseHandle(h_process)

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:515, in _ThreadpoolInfo._make_module_from_path(self, filepath)
    513 if prefix in self.prefixes or user_api in self.user_api:
    514     module_class = globals()[module_class]
--> 515     module = module_class(filepath, prefix, user_api, internal_api)
    516     self.modules.append(module)

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:606, in _Module.__init__(self, filepath, prefix, user_api, internal_api)
    604 self.internal_api = internal_api
    605 self._dynlib = ctypes.CDLL(filepath, mode=_RTLD_NOLOAD)
--> 606 self.version = self.get_version()
    607 self.num_threads = self.get_num_threads()
    608 self._get_extra_info()

File c:\\Users\\JOJO\\anaconda3\\lib\\site-packages\\threadpoolctl.py:646, in _OpenBLASModule.get_version(self)
    643 get_config = getattr(self._dynlib, \"openblas_get_config\",
    644                      lambda: None)
    645 get_config.restype = ctypes.c_char_p
--> 646 config = get_config().split()
    647 if config[0] == b\"OpenBLAS\":
    648     return config[1].decode(\"utf-8\")

AttributeError: 'NoneType' object has no attribute 'split'"
}

**Comment by hengzhe-zhang** [comment]
Could you upgrade your `threadpoolctl` package? I guess the error may be caused by some outdated packages.

**Comment by YinMengjiao** [comment]
> Could you upgrade your `threadpoolctl` package? I guess the error may be caused by some outdated packages.

threadpoolctl 已经是最新的3.2.0版本
还是跑不通啊
https://www.kaggle.com/code/jojoyin/evolutionary-forest
请您看一下我在kaggle里跑的过程
就是一直报错

**Comment by hengzhe-zhang** [comment]
> > Could you upgrade your `threadpoolctl` package? I guess the error may be caused by some outdated packages.
> 
> threadpoolctl 已经是最新的3.2.0版本 还是跑不通啊 https://www.kaggle.com/code/jojoyin/evolutionary-forest 请您看一下我在kaggle里跑的过程 就是一直报错

Is that a private Kaggle notebook? Please make it public, as I cannot access it due to a 404 error. Thanks.

**Comment by YinMengjiao** [comment]
> > > Could you upgrade your `threadpoolctl` package? I guess the error may be caused by some outdated packages.
> > 
> > 
> > threadpoolctl 已经是最新的3.2.0版本 还是跑不通啊 https://www.kaggle.com/code/jojoyin/evolutionary-forest 请您看一下我在kaggle里跑的过程 就是一直报错
> 
> Is that a private Kaggle notebook? Please make it public, as I cannot access it due to a 404 error. Thanks.

OK, I made it public.
![网页捕获_15-12-2023_16614_www kaggle com](https://github.com/hengzhe-zhang/EvolutionaryForest/assets/150641441/fd67483b-c0b7-4bc0-bd3f-df9d517440e3)

**Comment by hengzhe-zhang** [comment]
Sorry, please change `n_process` from 64 to 1. The multi-processor feature has become invalid after several versions of major changes. I will attempt to raise an exception in such a case in upcoming short-term versions.
