### ISSUE TITLE
How to add time series functions

### ISSUE THREAD

**Issue by Ray-0403** [hengzhe-zhang/EvolutionaryForest#92]
Hi, can u provide a guide to add time series functions like rolling mean, std to it? thank you

**Comment by hengzhe-zhang** [comment]
Thanks for your interest. A practical approach is to use a sliding window to transform time-series data into a tabular format. This technique is commonly used when applying models like XGBoost to time-series data. Once transformed, you can apply this framework to standardized tabular data.

**Comment by Ray-0403** [comment]
Ok, so I got this error when I try to add more primitives, what do I do? I saw there are many primitives available, how can I add all the available primitives to it.![image](https://github.com/hengzhe-zhang/EvolutionaryForest/assets/49976973/78b0ebcb-edba-4931-8497-bfe1b8dc60cb)

**Comment by hengzhe-zhang** [comment]
![image](https://github.com/hengzhe-zhang/EvolutionaryForest/assets/18747119/b18cff86-4e6c-40bf-9fec-15f9ab4d33c8)

Hi! Primitives are acronymized for ease of use. If you would like to use more predefined operators, please use these acronyms.
